services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lportal
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - liferay-net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  liferay:
    image: liferay/portal:7.4.3.132-ga132
    container_name: liferay-container
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    environment:
      LIFERAY_JDBC_DEFAULT_URL: jdbc:mysql://mysql:3306/lportal?useSSL=false&serverTimezone=UTC
      LIFERAY_JDBC_DEFAULT_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      LIFERAY_JDBC_DEFAULT_USERNAME: root
      LIFERAY_JDBC_DEFAULT_PASSWORD: root
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000
    ports:
      - "8080:8080"
      - "8000:8000"
    volumes:
      - ./liferay/data:/opt/liferay/data
      - ./liferay/deploy:/opt/liferay/deploy
      - ./liferay/osgi/configs:/opt/liferay/osgi/configs
      - ./liferay/osgi/modules:/opt/liferay/osgi/modules
    networks:
      - liferay-net

networks:
  liferay-net:
    driver: bridge

volumes:
  mysql-data: